### ISSUE TITLE
31.05.2018 - Semestersitzung

### ISSUE THREAD

**Issue by matthiasmeierkoch** [matthiasmeierkoch/Aufgaben#4]
Traktanden für die Semestersitzung:

**Comment by niciwatri** [comment]
– oft fehlt der Bezug vom Fach zu Interaktion design: was sind die lerninhalte?
– Wenig bis keine Theorie: Aufgabe wird verteilt und fertig
– riesige Projekte in kurzer Zeit: Wieso nicht aufteilen?: in einem Fach Texten, im anderen gestalten, usw. und am Schluss alles zusammenfügen...
– Wäre froh wenn Lehrer mehr von sich aus Inputs und Hilfe leisten anstelle das wir ihnen alles zur Nase rausziehen müssen... Ist natürlich nicht bei allen Lehrern so

**Comment by mariusbecker** [comment]
Kann mich niciwatri anschliessen
• Flipperchaschte id Mensa stelle

**Comment by ghost** [comment]
Meistens zu wenig Unterricht.
> es bringt nicht viel weiter, an Projekten zu schrauben ganz ohne Einführung oder jegliche Inputs. Best, schlechtestes Beispiel die Projektwoche.

**Comment by matthiasmeierkoch** [comment]
@niciwatri @mariusbecker das Protokoll zur Semestersitzung findet ihr unter folgendem Link, wir haben versucht möglichst alle Punkte einzubringen.
https://etherpad.gnome.org/p/IAD2017-Semestersitzung-2018-05-31
